### ISSUE TITLE
 Error: no matching Route53Zone found

### ISSUE THREAD

**Issue by DVAlexHiggs** [1Password/scim-examples#226]
Hi.

I'm trying to use the AWS Fargate Terraform script. So far I have had no luck running it. There seems to be pre-requisites of set up that are neither in the `PREPARATION.md` nor the the `README.md`, because it keeps giving me various errors about things not being available. I have not set anything up in AWS in advance, as I assumed the terraform script would be self-contained and do all of the set up for me.

Whenever I run the script, I get the following error

```
│ Error: no matching Route53Zone found
│ 
│   with data.aws_route53_zone.zone[0],
│   on main.tf line 101, in data "aws_route53_zone" "zone":
│  101: data "aws_route53_zone" "zone" {
```

My `terraform.tfvars` file, redacted

```hcl
# Required: Set a domain name for your SCIM bridge
domain_name = "scim.<my-domain>.com"

# Optional: Specify a different region
aws_region = "eu-west-2"

# Optional: Specify an existing VPC to use, add a common name prefix to all resources, specify the CloudWatch Logs retention period, and add tags for all supported resources.
vpc_name           = ""
name_prefix        = "scim-1password"
log_retention_days = 3

tags = {
  service = "1password"
}

# Uncomment the below line to use an existing wildcard certificate in AWS Certificate Manager.
#wildcard_cert = true

# Uncomment the below line if you are *not* using Route 53
#using_route53 = false

# Uncomment the below line to enable Google Workspace configuration for 1Password SCIM bridge
#using_google_workspace = true
```

### What I have tried

I have tried to create a Route53 Zone manually, however the error still occurs

If I uncomment the `using_route53 = false` then I get this error instead:

```
╷
│ Error: error creating ELBv2 Listener (arn:aws:elasticloadbalancing:eu-west-2:592415678207:loadbalancer/app/scim-1password-alb/f1040eee7987c466): UnsupportedCertificate: The certificate 'arn:aws:acm:eu-west-2:592415678207:certificate/46643f87-39a2-4331-bc34-c7b566b48ebd' must have a fully-qualified domain name, a supported signature, and a supported key size.
│       status code: 400, request id: af4d0b61-a773-48fc-8272-9d025e6ccdd5
│ 
│   with aws_lb_listener.https,
│   on main.tf line 258, in resource "aws_lb_listener" "https":
│  258: resource "aws_lb_listener" "https" {
│ 
```

And, If I look in the console, I do not have a certificate with my configured domain name.

So, my question is, what am I supposed to do here? Am I supposed to have set up Route53 or a certificate before running this script, if so, why?

Thanks in advance

**Comment by scottisloud** [comment]
Hi @DVAlexHiggs, do you own a domain that is managed by Route53? Although this Terraform plan does a lot, it will not purchase a new domain for you in Route53. You'll have to purchase or otherwise manage your domain in Route53. Once you have a domain managed by Route53, you can set `domain-name` to the value you want (e.g., `scim.<Route53-managed-domain>.com`) and the script will create that `scim` subdomain (or whatever subdomain you choose) for you at the existing domain managed by Route53. 

Assuming you are running the plain as-is, using Route53 for your domain, the plan will provision everything you need, including a TLS cert in ACM. 

If you have any additional issues please reach out to your 1Password Customer Success Manager or Account Manager to have them connect you to the right folks to support you. You can also reach out to our business support team businesssupport@1password.com for assistance from our integrations support team.

Hope that helps clarify what all this terraform plan does and I do encourage you to reach out to support or your 1Password Customer Success Manager to get connected with help through our formal support channels. :)

**Comment by DVAlexHiggs** [comment]
Thank you! This has helped

**Comment by scottisloud** [comment]
Oh great! Glad to hear it! Of course if you run into any further issues, never hesitate to reach out to your 1Password contact or businesssupport@1password.com and we'll be happy to help sort things out! :)
