### ISSUE TITLE
AWS Terraform deployment example egress requirements can be too restrictive

### ISSUE THREAD

**Issue by ag-adampike** [1Password/scim-examples#238]
Changes introduced in #220 seem to cause issues in some customers' AWS environments. Egress is currently restricted to TCP traffic on port 443 to allow SCIM bridge to reach 1Password.com servers.

Example error:

```
ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret arn:aws:secretsmanager:us-east-1:…:secret:op-scim-bridge-sercretARN from secrets manager: RequestCanceled: request context canceled caused by: context deadline exceeded. Please check your task network configuration.
```

A known workaround is to allow egress to anywhere for the `aws_security_group.service` resource, but further investigation is needed to reproduce and determine appropriate relaxations.

**Comment by davidwhite-edb** [comment]
Am I correct that this Terraform code only creates 1 security group?
`aws_security_group.alb: Creation complete after 4s [REDACTED]`

I'm running into this same symptom, but am not positive if it is due to the issue you have described here.

Ingress (inbound into the ALB) on this security group is allowing 443/tcp from anywhere already (0.0.0.0/0)
Egress (Outbound from the ALB), for the traffic originating from this AWS, resource has a rule that allows 3002/tcp over to other parts of our AWS Network.

I updated the Outbound rule on this ALB sg to allow 3002/tcp destined *to* 0.0.0.0/0, which did not resolve the issue.
I then *added* an outbound (egress) rule on this same ALB sg to allow 443/tcp destined to 0.0.0.0/0, which also did not resolve the issue. 

So I'm not sure if my problem is a direct result of of this same issue (your note about changes in #220 ) or not.

**Comment by scottisloud** [comment]
We may have a lead on a potential fix, though neither my teammates nor I have had a chance to dig into the details yet. Based on [this documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html), it _may_ just be a matter of ensuring `aws_security_group.service` has access to the private IP of the Route53 resolver for the VPC, rather than the public IP that it seems to be defaulting to. 

I'm sharing this in case it helps you in the short term, and we will update this issue as we are able to commit our own resources to testing and implementing the fix into the TF plan.

**Comment by davidwhite-edb** [comment]
You rock! I can confirm that adding 53/tcp udp access to 0.0.0.0/0 in the outbound (egress) rules for the `aws_security_group.service` resource fixes the issue. I'm sure we can lock that down further, but this confirms your theory.

**Comment by scottisloud** [comment]
Hi @davidwhite-edb, right back atcha! Thanks for being an intrepid Terraformer and giving this a shot and feeding your findings back! 

Enjoy your new SCIM bridge! :)

**Comment by davidwhite-edb** [comment]
Well, now the ConfirmationWatcher health check is failing when I login with my Bearer Token, so I'll troubleshoot that further and report back if/when that goes green again. Thanks again!

**Comment by davidwhite-edb** [comment]
Actually, I think that's a non-issue. Looks like we just need to turn on provisioning at this point.

`{......Server: (403) (Forbidden (Provisioning Disabled)), You can't perform this action because Provisioning is off. Turn Provisioning on, and try again.....}`

**Comment by davidwhite-edb** [comment]
I ran into this issue again today. 

I think (but am not positive) that the following code would mirror what I did back in August, and which I re-applied today, manually through the AWS console:

`david.white@MAC-MXGPRXTN2K aws-ecsfargate-terraform % git diff main.tf 
diff --git a/aws-ecsfargate-terraform/main.tf b/aws-ecsfargate-terraform/main.tf
index ccf1ad3..945dba1 100644
--- a/aws-ecsfargate-terraform/main.tf
+++ b/aws-ecsfargate-terraform/main.tf
@@ -238,6 +238,13 @@ resource "aws_security_group" "service" {
     cidr_blocks = ["0.0.0.0/0"]
   }
 
+  egress {
+    from_port   = 53
+    to_port     = 53
+    protocol    = "udp"
+    cidr_blocks = ["0.0.0.0/0"]
+  }
+
   tags = local.tags
 }`

**Comment by ag-adampike** [comment]
Thanks for the update, @davidwhite-edb! I've got a PR that is ready to merge later today to address this in our documentation.

I would recommend looking at the DNS attributes for the VPC for your SCIM bridge (see [View and update DNS attributes for your VPC](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating). If `DNS resolution` is enabled, you should not need to adjust the security groups as defined in the Terraform example.

Adding this egress rule to the security group as you've described should enable DNS resolution if that is not possible or desired.
